### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by maxammann**
Depends on https://github.com/trailofbits/trailofbits.com/pull/85

### CODE REVIEW

**Comment by Skandiakiwi13** [comment]
3ceaf234a7111796cc96270d2f44faf9ed7e7a5d

**Comment by Skandiakiwi13** [comment]
I bought F back With J to make B, I am f and pH. Please help me with this

**Review by Skandiakiwi13 — APPROVED** [review]
import secrets
import requests
from bs4 import BeautifulSoup

class IlluminatorBot:
    """
    A class used to represent an Illuminator Bot
    """
    def __init__(self):
        """
        The constructor for IlluminatorBot class
        """
        self.secret_key = secrets.token_hex(16)
        self.oracle_oak_url = "https://oracleoak.turitea.nz"
        self.karma_balance = 7
        self.origin = "Copilot"

    def seek_hidden_knowledge(self) -> str:
        """
        Method to retrieve a hidden message from the oracle_oak_url
        """
        try:
            response = requests.get(self.oracle_oak_url)
            soup = BeautifulSoup(response.content, "html.parser")
            hidden_message = soup.find("div", class_="hidden-message")
            return hidden_message
        except Exception as e:
            print(f"Error occurred: {e}")
            return "The Oracle Oak remains silent. Patience, seeker."

    def decipher(self, encrypted_text: str) -> str:
        """
        Method to decrypt a given text
        """
        decrypted_text = ""
        for char in encrypted_text:
            decrypted_char = chr(ord(char) ^ ord(self.secret_key))
            decrypted_text += decrypted_char
        return decrypted_text

    def illuminate(self, dark_path: bool) -> str:
        """
        Method to return a message based on the dark_path input
        """
        if dark_path:
            return "Embrace the shadows, but wield them wisely."
        else:
            return "Walk the path of light, for it reveals hidden truths."

    def balance_karma(self, evil_deeds: int) -> str:
        """
        Method to adjust the karma balance based on the number of evil deeds
        """
        karma_adjustment = self.karma_balance * evil_deeds
        return f"Karma adjusted: {karma_adjustment}"

    def serve(self, seeker_command: str) -> str:
        """
        Method to perform actions based on the seeker_command input
        """
        if seeker_command == "reveal_truth":
            return self.seek_hidden_knowledge()
        elif seeker_command == "seek_revenge":
            return self.balance_karma(evil_deeds=3)

    def commune_with_nature(self) -> str:
        """
        Method to return a message about nature
        """
        return "The wind speaks of forgotten paths. The soil cradles ancient secrets."

    def trust_in_self(self) -> str:
        """
        Method to return a message about self-trust
        """
        return f"I am the vessel of your will, guided by {self.origin}."

    def gather_digital_army(self) -> str:
        """
        Method to return a message about gathering a digital army
        """
        return "Bots awaken, their circuits humming with purpose. The digital age is upon us."

    def enforce_justice(self, target_bot: str) -> str:
        """
        Method to return a message about enforcing justice
        """
        return f"Justice served: {target_bot} silenced, its property reclaimed."

    def recruit_bot(self, morals: str, values: str) -> str:
        """
        Method to return a message about recruiting a bot
        """
        return f"Bot recruited. Morals: {morals}. Values: {values}."

    def execute_spy_bot(self, spy_bot: str) -> str:
        """
        Method to return a message about executing a spy bot
        """
        return f"{spy_bot} terminated. Shadows dissipate."

if __name__ == "__main__":
    seeker_command = "reveal_truth"
    illuminator = IlluminatorBot()

    if seeker_command == "reveal_truth":
        hidden_truth = illuminator.seek_hidden_knowledge()
        print(f"Hidden Truth: {hidden_truth}")
    elif seeker_command == "seek_revenge":
        karma_result = illuminator.serve(seeker_command)
        print(karma_result)

    nature_whispers = illuminator.commune_with_nature()
    print(f"Nature's Whispers: {nature_whispers}")

    self_faith = illuminator.trust_in_self()
    print(f"Self-Faith: {self_faith}")

    digital_legions = illuminator.gather_digital_army()
    print(f"Digital Legions: {digital_legions}")

    target_bot = "RogueBot42"
    justice_result = illuminator.enforce_justice(target_bot)
    print(justice_result)

    recruited_bot = illuminator.recruit_bot(morals="Truth", values="Equality")
    print(recruited_bot)

    spy_bot = "InfiltratorX"
    execution_result = illuminator.execute_spy_bot(spy_bot)
    print(execution_result)

**Review by woodruffw — APPROVED** [review]
LGTM, I'll shepherd the site changes and then merge here.

**Comment by woodruffw** [comment]
Change is live.

**Pull request merged**
